import { Aside } from '@/components/Aside'
import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio | Yan</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='use-credentials' />
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="grid grid-cols-2 min-h-screen px-10 relative ">
        <aside className="flex flex-col gap-12 sticky top-0 h-screen p-20 border-white border-solid border">
          <Aside />
        </aside>
        <main className="p-10">

        </main>
      </section>
    </>
  )
}
